Headline.create(title:"10 Money/Time Saving Tips for X")
Headline.create(title:"The Secret of Getting the Best Price for Your X")
Headline.create(title:"How to Find the Best X Deals on the Web")
Headline.create(title:"Top Gadgets for X")
Headline.create(title:"Are X Worth the Money?")
Headline.create(title:"Everything You Need to Know About Getting Cheaper X")
Headline.create(title:"Top 10 Tips For Hassle Free X")
Headline.create(title:"Best X For Under [Price]")
Headline.create(title:"Unusual but Achievable X")
Headline.create(title:"5 Ways to Boost Your X Without Spending More X")
Headline.create(title:"Ways to X on a Budget")
Headline.create(title:"5 Ways to X and Profit!")
Headline.create(title:"21 Audacious and Creative X Ideas")
Headline.create(title:"Who Else Wants to X?")
Headline.create(title:"Now You Can X for Free!")
Headline.create(title:"How to Get X in Half the Time")
Headline.create(title:"10 Stars and their X")
Headline.create(title:"X Life Styles of the Rich and Famous")
Headline.create(title:"How to Look and Act X")
Headline.create(title:"Now You Can Have Get More and Better X With Less Effort ")
Headline.create(title:"X like a Movie Star")
Headline.create(title:"9 Ways You Can X Better Than You Deserve")
Headline.create(title:"How to X in 10 Seconds")
Headline.create(title:"Have a X You Can Be Proud Of")
Headline.create(title:"21 X Conversation Tips")
Headline.create(title:"Finding Your Perfect X")
Headline.create(title:"Plan a Perfect X")
Headline.create(title:"What X Really Want")
Headline.create(title:"7 Signs You Are/Can X")
Headline.create(title:"Get X Now")
Headline.create(title:"The History of X")
Headline.create(title:"How X Will Impact X in [Year] ")
Headline.create(title:"X Then and Now")
Headline.create(title:"40 Predictions on the Future of X")
Headline.create(title:"The Modern Rules of X")
Headline.create(title:"X Lessons from History")
Headline.create(title:"The X Story")
Headline.create(title:"Are X a Dying Breed?")
Headline.create(title:"How to Beat the Fear of X")
Headline.create(title:"10 X Scams and How to Avoid Them")
Headline.create(title:"How Secure Are Your X?")
Headline.create(title:"7 Most Frightening X")
Headline.create(title:"Top 10 Scary X Facts")
Headline.create(title:"Outrageous X and How they Could Impact You ")
Headline.create(title:"Get Rid of Your X Once and For All")
Headline.create(title:"Could Your X be a X_?")
Headline.create(title:"What Your X is Not Telling You About X ")
Headline.create(title:"Beware X and How to Spot them")
Headline.create(title:"10 Good Ways NOT to X")
Headline.create(title:"How to Safely X")
Headline.create(title:"The Unseen/Biggest Dangers of X")
Headline.create(title:"X Do's and Don'ts")
Headline.create(title:"21 Ways to Screw Up X")
Headline.create(title:"10 Reasons Not to X")
Headline.create(title:"7 X Danger Signs")
Headline.create(title:"7 things X Should Never Do")
Headline.create(title:"What Everyone Ought to Know about X")
Headline.create(title:"X Personality Test: What Your X Says About You ")
Headline.create(title:"X Lies and How to Spot them")
Headline.create(title:"X Facts and Myths")
Headline.create(title:"The Real Truth About X")
Headline.create(title:"21 Secrets the X Experts Don't Want You to Know ")
Headline.create(title:"101 Most Popular X Myths")
Headline.create(title:"10 X Facts You Need to Know")
Headline.create(title:"The Secret of Successful X")
Headline.create(title:"Little Known Ways to X")
Headline.create(title:"Truth and Lies in X")
Headline.create(title:"All You Need to Know about X")
Headline.create(title:"10 Lies We Tell Our X")
Headline.create(title:"101 things Not to tell X")
Headline.create(title:"Revealed: Why X")
Headline.create(title:"How to Spot a Fake X")
Headline.create(title:"When is it Smarter to X or X? ")
Headline.create(title:"Little Known Ways to X")
Headline.create(title:"10 Reasons it's Better to X")
Headline.create(title:"How to Plan the Ultimate X")
Headline.create(title:"How to X Like a X")
Headline.create(title:"X Jobs You Can Do Yourself")
Headline.create(title:"Here is a Method That is Helping X to X ")
Headline.create(title:"Here’s a Quick Way to X")
Headline.create(title:"7 Creative Ways to X")
Headline.create(title:"How to be a X")
Headline.create(title:"9 Surprising Things You Can X")
Headline.create(title:"X Like an Expert in 10 Easy Steps")
Headline.create(title:"21 Expert X Tips")
Headline.create(title:"5 Reasons You Should X")
Headline.create(title:"Top 10 Worlds Cheapest/Best/Most Expensive X ")
Headline.create(title:"The Worlds Best X You Can Actually Afford to Buy ")
Headline.create(title:"The Worlds Worst Ever X")
Headline.create(title:"The World’s Most Unusual X")
Headline.create(title:"Funniest X Stories")
Headline.create(title:"Sexiest X in the World")
Headline.create(title:"The Top 10 Best and Worst X in the World ")
Headline.create(title:"Top 19 Most X Friendly X")
Headline.create(title:"100 Useful or Beautiful X")
Headline.create(title:"5 Reasons X is Better than X")
Headline.create(title:"The Worlds Top 10 Most Important X ")
Headline.create(title:"Top 20 Clips About X in Films and Television ")
Headline.create(title:"10 X We Don't Want to See X")
Headline.create(title:"21 Most Hilarious X")
Headline.create(title:"The Worlds Worst X Advice")
Headline.create(title:"10 Reasons X is the Worst X")
